### ISSUE TITLE
No support for .NET 4.5 and up

### ISSUE THREAD

**Issue by VashBaldeus** [AlexanderAnishchik/Credit-Card-Stripe-Parser#1]
This library does not have support for .NET 4.5 and up.
I used this project source to recreate this library with support of .NET 4.5 and up

If original creator gives permission I will publish it.

**Comment by AlexanderAnishchik** [comment]
@VashBaldeus The project is developed on .NET Standard 2.0 that only supported on .NET Framework 4.6.1 and above. https://github.com/dotnet/standard/blob/master/docs/versions.md
There are no plans to support version below 4.6.1. I can suggest you to update your target framework. Thanks for the information.
